### ISSUE TITLE
assert(os.path.exists(PASS_DIR))

### ISSUE THREAD

**Issue by jgarte** [OliverLew/cpass#4]
Hi, 

I was packaging cpass for [guix](guix.gnu.org) and I get the following error:

Do you happen to know what might be causing it.

```
Traceback (most recent call last):
  File "/gnu/store/36dx52423ipqw2hs5cx392dwr8dysf59-cpass-guixrus-0.9.2/bin/.cpass-real", line 11, in <module>
    load_entry_point('cpass==0.9.2', 'console_scripts', 'cpass')()
  File "/gnu/store/sd2ic7bpv8fx3imy1j8xcjclx71sv6q0-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/gnu/store/sd2ic7bpv8fx3imy1j8xcjclx71sv6q0-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/gnu/store/sd2ic7bpv8fx3imy1j8xcjclx71sv6q0-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/gnu/store/sd2ic7bpv8fx3imy1j8xcjclx71sv6q0-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/gnu/store/36dx52423ipqw2hs5cx392dwr8dysf59-cpass-guixrus-0.9.2/lib/python3.8/site-packages/cpass.py", line 524, in <module>
    class Pass:
  File "/gnu/store/36dx52423ipqw2hs5cx392dwr8dysf59-cpass-guixrus-0.9.2/lib/python3.8/site-packages/cpass.py", line 531, in Pass
    assert(os.path.exists(PASS_DIR))
AssertionError
```

**Comment by jgarte** [comment]
Oh ok.

I needed to add the following to my `~/.bashrc`:

`export PASSWORD_STORE_DIR=$HOME/.password-store`

I discovered after reading https://github.com/OliverLew/cpass/blob/main/cpass.py#L523 and https://github.com/OliverLew/cpass#requirement

Should `cpass` emit a friendly warning if `PASSWORD_STORE_DIR` is not set instead of hard failing with a traceback?

I can send a pull request for that if you'd like.

**Comment by xlucn** [comment]
It seems my bad choice for checking the existence of the passwordstore directory. If the default directory ($HOME/passwordstore/ or $PASSWORD_STORE_DIR/) doesn't exist, then this is expected now, and I should change from showing an error with traceback to a more user-friendly warning.

> Should `cpass` emit a friendly warning if `PASSWORD_STORE_DIR` is not set instead of hard failing with a traceback?

Yes :)
